mixnjuice/api

LICENSE
package.json

I had left the default info in the author field during `npm init` - now that this repo is part of the organization I feel like we should do what other large projects do and have no author information in the package.json. At some point in the future we can create a separate document with a list of contributors when necessary.
This also changes the package name to move it under the `@gusta` npm namespace/organization.

Move package under gusta namespace, remove author field from package.json

---

package-lock.json
package.json

We are currently using a version of lodash that is vulnerable to prototype pollution as documented [here](https://snyk.io/vuln/SNYK-JS-LODASH-450202) and in https://github.com/lodash/lodash/issues/4348. 
Fix is to force selection of the latest versions of lodash and lodash.merge.

Upgrade lodash to resolve security vulnerability

---

README.md
package-lock.json
package.json
src/modules/auth.js
src/modules/config.js
src/routes/flavor.js
src/routes/flavor.test.js

This PR makes the following changes:
* [Adds](https://github.com/gusta-project/api/compare/master...ayan4m1:feature/auth-configuration#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R25) passport-anonymous for auth bypass strategy and [cross-env](https://github.com/gusta-project/api/compare/master...ayan4m1:feature/auth-configuration#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R41) to let us set env vars in package.json scripts
* [Adds](https://github.com/gusta-project/api/compare/master...ayan4m1:feature/auth-configuration#diff-76d9f4cd95a06ef858497eeec21d9c8cR22) the API_TOKEN_VALIDATE boolean env var to the config, defaulting to `true` if the env var is not specified (adding this to the `.env.default` wouldn't work here as we need the environment to override the `.env` file)
* …

Add authentication bypass mechanism to app config

---

schema/07.do.preparations-diluents.sql
schema/07.undo.preparations-diluents.sql
src/models/preparationsDiluents.js

This PR makes a few schema changes and adds a missing model.
The `preparation` table did not have a correct primary key, that is fixed [here](https://github.com/gusta-project/api/compare/master...ayan4m1:feature/prep-diluents?expand=1#diff-6fea68894039b7c348b2dbe3ad3346bdR1). Next I [created](https://github.com/gusta-project/api/compare/master...ayan4m1:feature/prep-diluents?expand=1#diff-6fea68894039b7c348b2dbe3ad3346bdR7) a table that was in my ERD but missing from the SQL. Finally, I [added](https://github.com/gusta-project/api/compare/master...ayan4m1:feature/prep-diluents?expand=1#diff-520f494942e311575bd137325f64dc03R1) a skeleton model for the new table.

Add missing preparations_diluents table

---

.circleci/config.yml

This PR modifies the CircleCI configuration to use a new orb that sends a webhook notification to our chat server on based on the success or failure of the unit tests.

Notify Mattermost via CircleCI

---

src/modules/auth.js

Currently the API stores an expiry time for a token in the database, but it does not send this information back to the frontend. This PR adds that in the form of the OAuth standard `expires_in` field, which is an integer number of seconds that the token will be valid for.

Add expires_in value to token exchange response

---

src/modules/auth.js

When the database is down or some other slow error occurs, the API is holding the HTTP response open and it times out in the browser. This PR calls the auth middleware in case of an error - the way it should have been from the start.

Return immediately in case of auth error (e.g. db is down)

---

schema/10.do.millipercent.sql
schema/10.undo.millipercent.sql

Currently most of the millipercent columns are erroneously declared as `NUMERIC(4, 4)` which is a fractional number. Instead, the goal is to keep the calculator math consistent and fast, and integers are more consistent and fast than decimals. Each millipercent column is now an integer from 0-10000 with 0 representing 0% and 10,000 representing 100%.

Convert all decimals into proper millipercent integers

---

src/modules/auth.js

Including the user ID in a successful OAuth token response so that the frontend knows the ID of the logged in user.

Send user ID back with successful auth response

---

schema/11.do.prep-diluents-pk.sql
schema/11.undo.prep-diluents-pk.sql

This PR changes the `preparations_diluents` table from using a composite PK over `(preparation_id, diluent_id)` to a single PK over a new `bigserial` column called `id`. This allows for the storage of preparations which have nicotine base with a PG/VG ratio different than that of the finished liquid.

Allow multiple diluents per preparation

---

jsconfig.json

Currently, you cannot Ctrl-click on imports that are auto-resolved to `index.js` e.g.
```js
import { something } from 'util';
```
Where there is a file `util/index.js`. This PR fixes that by using the correct `module` setting for the JS/TS compiler options.

Fix VS Code ctrl-click on index modules

---

schema/12.do.tag-and-version.sql
schema/12.undo.tag-and-version.sql
src/models/recipe.js
src/models/tag.js
src/models/tagsFlavors.js
src/models/tagsRecipes.js

This PR adds schema which allows users to tag flavors and recipes with arbitrary strings. It also modifies the `recipe` table so that recipes can be versioned. To do this, it adds a `version` column which is intended to be a monotonically increasing integer starting at 1. Each subsequent version has a `parent_id` set to the prior version's recipe ID.

Schema for recipe versioning and flavor/recipe tagging

---

schema/13.do.unique-role-name.sql
schema/13.undo.unique-role-name.sql

This PR adds a miss caught by @daviddyess - namely, there is no unique constraint on the role `name` column, which could lead to complicated mistakes. Make sure that you manually deduplicate before attempting migration!

Add missing unique constraint on role.name

---

src/models/recipe.js
src/models/tag.js
src/models/user.js

Some models were trying to use the incorrect foreign key resulting in queries like:
> SELECT "id", "email_address" AS "emailAddress", "password", "created", "activation_code" AS "activationCode", "creator_id" AS "creatorId" FROM "user" AS "User" WHERE "User"."email_address" = 'someone@email.org' AND "User"."activation_code" IS NULL;
This results in column not found errors because creator_id is not a column on the user table. [This change](https://github.com/gusta-project/api/compare/master...ayan4m1:fix/user-model?expand=1#diff-9cde3d777f4c1ebe697276b63c7aea1bR41) fixes that issue, while [this one](https://github.com/gusta-project/api/compare/master...ayan4m1:fix/user-model?expand=1#diff-9cde3d777f4c1ebe697276b63c7aea1bR41) and [this …

Fix models still using userId instead of creatorId

---

gulpfile.babel.js
package-lock.json
package.json

This PR adds [gulp-nodemon](https://www.npmjs.com/package/gulp-nodemon) and updates a package.json script so that you can do:
> npm run watch
or 
> npx gulp watch
And you will get an instance of the API that recompiles and reloads when files in `src/` are changed.

Add gulp-nodemon

---

src/routes/data.js
src/routes/diluent.js
src/routes/diluents.js
src/routes/flavor.js
src/routes/flavors.js
src/routes/preparation.js
src/routes/preparations.js
src/routes/recipe.js
src/routes/recipes.js
src/routes/role.js
src/routes/roles.js
src/routes/user.js
src/routes/users.js
src/routes/vendor.js
src/routes/vendors.js

This PR makes two changes.
I went over all of the routes and looked for places where we were either treating the results of `findOne` as an array and replaced these checks with simple null checks instead, because findOne never returns an array. I also added `Array.isArray(result)` assertions to all of the calls to `findAll` before checking its `length` property.
The other change is to some of the queries that were using nested `include` sections in order to query through models. Now that we have `belongsToMany` associations, that is not necessary (or valid since the models aren't directly associated anymore). I changed these queries to use the correct associations, and removed some instances of `required: true` on models that we don't want to inner join to.

Fix queries and empty checks in routes

---

src/models/recipe.js
src/models/tag.js

This PR resolves two issues with the models:
* An association to [UserProfile](https://github.com/gusta-project/api/compare/master...ayan4m1:fix/models?expand=1#diff-9dc1f788cd7f661a552c2e001c185d20R71) still had userId instead of creatorId
* I [reversed](https://github.com/gusta-project/api/compare/master...ayan4m1:fix/models?expand=1#diff-9cde3d777f4c1ebe697276b63c7aea1bR43) the belongsToMany associations in the tag, which were incorrect

Fix model setup

---

schema/14.do.remove-recipe-constraint.sql
schema/14.undo.remove-recipe-constraint.sql

This PR removes the `uk1_recipe` key from the recipe table, which prevents users from have multiple recipes with the same name. This will break recipe versioning so it needs to go.
Also, add a default view_count of 0 for the recipe table.

Add default recipe.view_count, remove recipe.uk1_recipe

---

package-lock.json
package.json
schema/15.do.drop-nic-millipercent.sql
schema/15.undo.drop-nic-millipercent.sql
src/models/preparation.js
src/models/recipe.js
src/models/recipesFlavors.js
src/modules/auth.js
src/modules/util.js
src/routes/data.test.js
src/routes/diluent.test.js
src/routes/diluents.test.js
src/routes/flavor.test.js
src/routes/flavors.test.js
src/routes/preparation.test.js
src/routes/preparations.test.js
src/routes/recipe.js
src/routes/recipe.test.js
src/routes/recipes.test.js
src/routes/register.test.js
src/routes/role.test.js
src/routes/roles.test.js
src/routes/stats.test.js
src/routes/user.test.js
src/routes/users.test.js
src/routes/vendor.test.js
src/routes/vendors.test.js

This PR makes the following changes:
* [Remove](https://github.com/mixnjuice/api/compare/master...ayan4m1:refactor/recipe-save?expand=1#diff-1e9c19ced524f8338efda6afe5e9b8afR1) a vestigial column from the preparation table
* [Set defaults](https://github.com/mixnjuice/api/compare/master...ayan4m1:refactor/recipe-save?expand=1#diff-5fff0d60851d23c3f1abb464c4a8b594R39) for viewCount fields
* [Adds](https://github.com/mixnjuice/api/compare/master...ayan4m1:refactor/recipe-save?expand=1#diff-9dc1f788cd7f661a552c2e001c185d20R87-R94) associations that make persistence of a recipe easier (no need to do lookups before inserting)
* [Overhaul](https://github.com/mixnjuice/api/compare/master...ayan4m1:refactor/recipe-save?expand=1#diff-fb331442c9dfca487b57de25ad9e179bR122-R128) the recipe request …

Recipe persistence

---

.circleci/config.yml

This PR fixes circleci failures introduced by #42 - the codecov line was not exporting its env var correctly and this was causing a build failure.
The change is to use the `-e` argument of `docker exec` to pass the codecov token through to the containerized process.

Fix codecov env var setup

---

package-lock.json
package.json
src/modules/database.js

This PR replaces the old package under the `gusta` npm namespace with the new `mixnjuice` name space. Code should be the same.

Replace @gusta/sequelize-mock with @mixnjuice/sequelize-mock

---

.circleci/config.yml
Dockerfile
README.md
package.json
src/modules/utils/test.js
src/modules/utils/test.test.js

* [Change](https://github.com/mixnjuice/api/compare/master...ayan4m1:feature/alpine-docker-image?expand=1#diff-3254677a7917c6c01f55212f86c57fbfR1) from Ubuntu to Alpine based base image for Docker builds. This cuts the image size in half and improves build speed. Because Alpine-compatible musl builds are not available for [bcrypt](https://www.npmjs.com/package/bcrypt) we have to [install build deps now](https://github.com/mixnjuice/api/compare/master...ayan4m1:feature/alpine-docker-image?expand=1#diff-3254677a7917c6c01f55212f86c57fbfR13)
* [Fix](https://github.com/mixnjuice/api/compare/master...ayan4m1:feature/alpine-docker-image?expand=1#diff-3254677a7917c6c01f55212f86c57fbfR15) an issue where building the Docker image on Windows hosts would result in a failure to start because the line …

Improve Docker image size, fix Jest hang

---

schema/17.do.recipe-share-key.sql
schema/17.undo.recipe-share-key.sql
src/models/recipe.js

This PR adds a `share_key` column to the `recipe` table and to the recipe.js model. This field default to null, but when set will allow us to look up a recipe by a shared secret without disclosing its other identifiers.

Add recipe share key column

---

src/app.js
src/migrate.js
src/modules/auth.js
src/modules/config.js
src/modules/config.test.js
src/modules/database.js
src/modules/utils/index.js
src/modules/utils/utils.test.js
src/routes/register.js

By breaking out the config module into separate `export const` objects we can import only those that matter to a given file.
I added an `isTrue` helper for determining if a dotenv-sourced config key is a string representation of a boolean. I added tests for this util.

Refactor config module to export individual concerns

---

schema/18.do.flavor-safety.sql
schema/18.undo.flavor-safety.sql
src/models/flavor.js
src/models/flavorsIngredients.js
src/models/ingredient.js
src/models/ingredientCategory.js

This PR adds the schema migration and Sequelize models for flavor safety information.
I have an SDS parser which is currently outputting data in CSV format that can be re-engineered to store its data in these tables. It associates a single flavor to one or more ingredients which are indicated by CAS number in the safety data sheets. I have created three categories for the ingredients of interest - "avoid," "caution," and "research." They are ranked ordinally so that we can show only the most important warnings in some places but show the full list in others.
Work to enhance endpoints to return this data will be done in another PR.

Add schema and models for flavor ingredient safety

---

.circleci/config.yml
src/routes/role.test.js

This PR fixes notifications to Mattermost about build failures. Currently, the setup does not work because the `notify` job only triggers if the previous job was successful. To resolve this, inline the notify steps in the build job, where their `when: on_fail` and `when: on_success` will now work as expected.

Fix Mattermost notifier failures

---

schema/18.do.flavor-safety.sql
schema/19.do.flavor-safety-links.sql
schema/19.undo.flavor-safety-links.sql

This PR fixes some of the static data for the flavor safety implementation and adds a new table, ingredient_link, which stores research/articles related to a particular ingredient.

Fix flavor safety data, add ingredient_link

---

.vscode/settings.json

This PR mirrors [this one](https://github.com/mixnjuice/frontend/pull/49) from the frontend repo. It fixes application of eslint and stylelint on save and removes a deprecated setting.

Update vscode settings for plugin/vscode config schema changes

---

schema/20.do.user-preferences.sql
schema/20.undo.user-preferences.sql

This PR adds a SQL migration that adds the following to the schema:
This will allow us to store and associate preference data to users. Data is stored in the `value` field of `users_preferences` as a JSON string.

Add user preferences migration scripts

---

schema/21.do.permissions.sql
schema/21.undo.permissions.sql
src/models/permissionAction.js
src/models/permissionSubject.js
src/models/rolesPermissions.js
src/modules/auth.js
src/routes/data.js
src/routes/diluent.js
src/routes/diluents.js
src/routes/flavor.js
src/routes/flavors.js
src/routes/preparation.js
src/routes/preparations.js
src/routes/recipe.js
src/routes/recipes.js
src/routes/role.js
src/routes/roles.js
src/routes/stats.js
src/routes/user.js
src/routes/users.js
src/routes/vendor.js
src/routes/vendors.js

Currently, there is an issue (identified by @daviddyess ) where anonymous users will not be able to fetch required API routes for the public pages (e.g. recipe view).
To resolve this, I have made the following changes:
* [Create](https://github.com/mixnjuice/api/compare/master...ayan4m1:feature/permissions-overhaul?expand=1#diff-137acb549024bd9d802e64d32a5b2146R1) three new tables in the schema - permission_subject, permission_action, and roles_permissions. Subjects and actions are defined per the [CASL](https://www.npmjs.com/package/@casl/ability) spec.
* [Insert](https://github.com/mixnjuice/api/compare/master...ayan4m1:feature/permissions-overhaul?expand=1#diff-137acb549024bd9d802e64d32a5b2146R28) starter permission_subject and permission_action values and add a Guest role
* …

Fix anonymous permissions issue

---

README.md

This PR addresses a small gap in the API documentation, adding in the missing "build" step that transpiles files to `lib/`

Add `npm run build` to README.md

---

src/routes/users.js

Updated the `/users/ route privilege subjects to `user`. It was set to `users`, which doesn't exist in the db.

/users Route Privilege Fix
